<?php
// install.php
// Simple installer for the Notice Board application

error_reporting(E_ALL);
ini_set('display_errors', 1);

$config_file = __DIR__ . '/php/db_config.php';
$sql_file = __DIR__ . '/tables.sql';
$steps = ['check', 'form', 'install', 'complete'];
$current_step = 'check';

// --- Step 1: Pre-installation Checks ---
$is_writable = is_writable(__DIR__ . '/php/');
$sql_readable = is_readable($sql_file);

if (file_exists($config_file)) {
    $current_step = 'complete'; // Already installed
} elseif ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $current_step = 'install';
} elseif ($is_writable && $sql_readable) {
    $current_step = 'form';
}

// --- Step 3: Installation Logic ---
if ($current_step === 'install') {
    $db_host = $_POST['db_host'] ?? 'localhost';
    $db_user = $_POST['db_user'] ?? '';
    $db_pass = $_POST['db_pass'] ?? '';
    $db_name = $_POST['db_name'] ?? '';

    $admin_user = $_POST['admin_user'] ?? '';
    $admin_pass = $_POST['admin_pass'] ?? '';
    $admin_school = $_POST['admin_school'] ?? '';
    $admin_email = $_POST['admin_email'] ?? '';

    $api_area = $_POST['api_area'] ?? '';
    $api_school = $_POST['api_school'] ?? '';

    $errors = [];

    // Validate inputs
    if (empty($db_host) || empty($db_user) || empty($db_name) || empty($admin_user) || empty($admin_pass) || empty($admin_school) || empty($admin_email)) {
        $errors[] = "모든 필수 필드를 입력해주세요.";
    }

    // Create DB connection
    $conn = new mysqli($db_host, $db_user, $db_pass);
    if ($conn->connect_error) {
        $errors[] = "데이터베이스 연결 실패: " . $conn->connect_error;
    } else {
        // Create database if it doesn't exist
        $conn->query("CREATE DATABASE IF NOT EXISTS `$db_name` CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci");
        $conn->select_db($db_name);
        if ($conn->error) {
            $errors[] = "데이터베이스 선택 실패: " . $conn->error;
        }
    }

    // Execute SQL from tables.sql
    if (empty($errors)) {
        $sql_content = file_get_contents($sql_file);
        if ($sql_content === false) {
            $errors[] = "tables.sql 파일을 읽을 수 없습니다.";
        } else {
            // Execute multi-query
            if ($conn->multi_query($sql_content)) {
                // Important to clear results of multi_query
                while ($conn->next_result()) {
                    if ($result = $conn->store_result()) {
                        $result->free();
                    }
                }
            } else {
                $errors[] = "테이블 생성 실패: " . $conn->error;
            }
        }
    }

    // Insert admin user
    if (empty($errors)) {
        $hashed_password = password_hash($admin_pass, PASSWORD_DEFAULT);
        $stmt = $conn->prepare("INSERT INTO users (username, password, school_name, email, api_area_code, api_school_code) VALUES (?, ?, ?, ?, ?, ?)");
        if ($stmt) {
            $stmt->bind_param("ssssss", $admin_user, $hashed_password, $admin_school, $admin_email, $api_area, $api_school);
            if (!$stmt->execute()) {
                $errors[] = "관리자 계정 생성 실패: " . $stmt->error;
            }
            $stmt->close();
        } else {
            $errors[] = "관리자 계정 생성 SQL 준비 실패: " . $conn->error;
        }
    }

    // Create db_config.php
    if (empty($errors)) {
        $config_content = "<?php\n";
        $config_content .= "// Database configuration generated by install.php\n";
        $config_content .= "define('DB_HOST', '" . addslashes($db_host) . "');\n";
        $config_content .= "define('DB_USER', '" . addslashes($db_user) . "');\n";
        $config_content .= "define('DB_PASS', '" . addslashes($db_pass) . "');\n";
        $config_content .= "define('DB_NAME', '" . addslashes($db_name) . "');\n\n";
        $config_content .= "\$conn = new mysqli(DB_HOST, DB_USER, DB_PASS, DB_NAME);\n\n";
        $config_content .= "if (\$conn->connect_error) {\n";
        $config_content .= "    die('Connection failed: ' . \$conn->connect_error);\n";
        $config_content .= "}\n";
        $config_content .= "\$conn->set_charset('utf8mb4');\n";

        if (file_put_contents($config_file, $config_content) === false) {
            $errors[] = "php/db_config.php 파일 생성에 실패했습니다. 폴더 권한을 확인해주세요.";
        }
    }

    $conn->close();

    if (empty($errors)) {
        $current_step = 'complete';
    }
}

?>
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>디지털 게시판 설치</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        body { font-family: 'Pretendard', sans-serif; }
        .form-label { @apply block text-sm font-medium text-gray-700 mb-1; }
        .form-input { @apply w-full p-2 border border-gray-300 rounded-md; }
        .form-section { @apply bg-white p-6 rounded-lg shadow-md mb-6; }
    </style>
</head>
<body class="bg-gray-100 flex items-center justify-center min-h-screen">
    <div class="w-full max-w-2xl mx-auto my-8">
        <header class="text-center mb-8">
            <h1 class="text-3xl font-bold text-gray-800">디지털 게시판 설치</h1>
        </header>

        <main>
            <?php if ($current_step === 'check'): ?>
                <div class="form-section text-red-600">
                    <h2 class="text-xl font-semibold mb-3">설치 오류</h2>
                    <p>설치를 진행할 수 없습니다. 아래 문제를 해결해주세요.</p>
                    <ul class="list-disc list-inside mt-2">
                        <?php if (!$is_writable): ?>
                            <li>`php` 폴더에 쓰기 권한이 없습니다. (<?php echo realpath(__DIR__ . '/php/'); ?>)</li>
                        <?php endif; ?>
                        <?php if (!$sql_readable): ?>
                            <li>`tables.sql` 파일을 읽을 수 없습니다. (<?php echo realpath($sql_file); ?>)</li>
                        <?php endif; ?>
                    </ul>
                </div>
            <?php endif; ?>

            <?php if ($current_step === 'form'): ?>
                <form action="install.php" method="POST">
                    <div class="form-section">
                        <h2 class="text-xl font-semibold mb-4 border-b pb-2">1. 데이터베이스 설정</h2>
                        <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4">
                            <div>
                                <label for="db_host" class="form-label">DB 호스트</label>
                                <input type="text" id="db_host" name="db_host" class="form-input" value="localhost" required>
                            </div>
                            <div>
                                <label for="db_name" class="form-label">DB 이름</label>
                                <input type="text" id="db_name" name="db_name" class="form-input" required>
                            </div>
                            <div>
                                <label for="db_user" class="form-label">DB 사용자</label>
                                <input type="text" id="db_user" name="db_user" class="form-input" required>
                            </div>
                            <div>
                                <label for="db_pass" class="form-label">DB 비밀번호</label>
                                <input type="password" id="db_pass" name="db_pass" class="form-input">
                            </div>
                        </div>
                    </div>

                    <div class="form-section">
                        <h2 class="text-xl font-semibold mb-4 border-b pb-2">2. 관리자 계정 생성</h2>
                        <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4">
                            <div>
                                <label for="admin_user" class="form-label">사용자명</label>
                                <input type="text" id="admin_user" name="admin_user" class="form-input" required>
                            </div>
                            <div>
                                <label for="admin_pass" class="form-label">비밀번호</label>
                                <input type="password" id="admin_pass" name="admin_pass" class="form-input" required>
                            </div>
                             <div>
                                <label for="admin_school" class="form-label">학교 이름</label>
                                <input type="text" id="admin_school" name="admin_school" class="form-input" required>
                            </div>
                            <div>
                                <label for="admin_email" class="form-label">이메일</label>
                                <input type="email" id="admin_email" name="admin_email" class="form-input" required>
                            </div>
                        </div>
                    </div>

                    <div class="form-section">
                        <h2 class="text-xl font-semibold mb-4 border-b pb-2">3. 나이스 API 설정 (선택 사항)</h2>
                        <p class="text-sm text-gray-600 mb-4">
                            급식 정보 연동을 위해 필요합니다. 
                            <a href="https://open.neis.go.kr/portal/data/service/selectServicePage.do?page=1&rows=10&sortColumn=&sortDirection=&infId=OPEN17320190722180924242823&infSeq=1" target="_blank" class="text-blue-600 hover:underline">여기</a>에서 학교 정보를 찾아 입력하세요.
                            이 정보는 나중에 관리자 페이지에서도 수정할 수 있습니다.
                        </p>
                        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                            <div>
                                <label for="api_area" class="form-label">시도교육청코드 (ATPT_OFCDC_SC_CODE)</label>
                                <input type="text" id="api_area" name="api_area" class="form-input" placeholder="예: J10">
                            </div>
                            <div>
                                <label for="api_school" class="form-label">행정표준코드 (SD_SCHUL_CODE)</label>
                                <input type="text" id="api_school" name="api_school" class="form-input" placeholder="예: 7530229">
                            </div>
                        </div>
                    </div>

                    <div class="text-center">
                        <button type="submit" class="bg-blue-600 text-white font-bold py-3 px-8 rounded-md hover:bg-blue-700 text-lg">
                            설치하기
                        </button>
                    </div>
                </form>
            <?php endif; ?>

            <?php if ($current_step === 'install' && !empty($errors)): ?>
                <div class="form-section bg-red-100 border border-red-400 text-red-700">
                    <h2 class="text-xl font-semibold mb-3">설치 실패</h2>
                    <p>다음 오류를 해결한 후 다시 시도해주세요:</p>
                    <ul class="list-disc list-inside mt-2">
                        <?php foreach ($errors as $error): ?>
                            <li><?php echo htmlspecialchars($error); ?></li>
                        <?php endforeach; ?>
                    </ul>
                    <div class="mt-4 text-center">
                         <a href="install.php" class="bg-gray-500 text-white font-bold py-2 px-6 rounded-md hover:bg-gray-600">
                            돌아가기
                        </a>
                    </div>
                </div>
            <?php endif; ?>

            <?php if ($current_step === 'complete'): ?>
                 <div class="form-section text-center">
                    <h2 class="text-2xl font-bold mb-4 text-green-600">🎉 설치 완료!</h2>
                    <p class="text-gray-700 mb-6">디지털 게시판 설치가 성공적으로 완료되었습니다.</p>
                    
                    <div class="bg-yellow-100 border-l-4 border-yellow-500 text-yellow-700 p-4 mb-6" role="alert">
                        <p class="font-bold">중요 보안 경고</p>
                        <p>보안을 위해, 지금 바로 서버에서 `install.php` 파일을 삭제해주세요!</p>
                    </div>

                    <p class="text-gray-600 mb-6">
                        데이터베이스 정보 등은 설치 후 <strong><?php echo htmlspecialchars($config_file); ?></strong> 파일에서 직접 수정할 수 있습니다.
                    </p>

                    <a href="login.html" class="bg-blue-600 text-white font-bold py-3 px-8 rounded-md hover:bg-blue-700 text-lg">
                        로그인 페이지로 이동
                    </a>
                </div>
            <?php endif; ?>
        </main>
    </div>
</body>
</html>
